FROM jenkins/jenkins:jdk21

# Copy in plugins.txt.
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt

# Install all plugins with with the included jenkins-plugin-cli.
RUN jenkins-plugin-cli --plugin-file /usr/share/jenkins/ref/plugins.txt

# Copy in jenkins.yaml.
COPY jenkins.yaml /usr/share/jenkins/ref/jenkins.yml

# Suppress the setup wizard and tell JCasC where the config file is located.
ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
ENV CASC_JENKINS_CONFIG="/usr/share/jenkins/ref/jenkins.yml"

EXPOSE 8080