pipeline {
    agent none

    options {
        ansiColor('xterm')
    }

    stages {
        stage('Matrix Build') {
            matrix {
                axes {
                    axis {
                        name 'NODE_VERSION'
                        values 'Node 20.x', 'Node 22.x'
                    }
                }

                agent any

                tools {
                    nodejs "${NODE_VERSION}"
                }

                stages {
                    stage('Install') {
                        steps {
                            dir('app') {
                                sh 'npm install'
                            }
                        }
                    }

                    stage('Test') {
                        parallel {
                            stage('Lint') {
                                steps {
                                    dir('app') {
                                        sh 'npm run lint'
                                    }
                                }
                            }
                            stage('Unit Tests') {
                                steps {
                                    dir('app') {
                                        sh 'npm run test:unit'
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
